require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MotionsController do

  # This should return the minimal set of attributes required to create a valid
  # Motion. As you add validations to Motion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "organization" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MotionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all motions as @motions" do
      motion = Motion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:motions).should eq([motion])
    end
  end

  describe "GET show" do
    it "assigns the requested motion as @motion" do
      motion = Motion.create! valid_attributes
      get :show, {:id => motion.to_param}, valid_session
      assigns(:motion).should eq(motion)
    end

    it "returns the correct motion in json format" do
      motion = FactoryGirl.create(:motion)
      get :show, id: motion.id, format: :json
      response.should be_success
      response.body.should eq(assigns(:motion).to_json)
    end
  end

  describe "GET new" do
    it "assigns a new motion as @motion" do
      get :new, {}, valid_session
      assigns(:motion).should be_a_new(Motion)
    end
  end

  describe "GET edit" do
    it "assigns the requested motion as @motion" do
      motion = Motion.create! valid_attributes
      get :edit, {:id => motion.to_param}, valid_session
      assigns(:motion).should eq(motion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Motion" do
        expect {
          post :create, {:motion => valid_attributes}, valid_session
        }.to change(Motion, :count).by(1)
      end

      it "assigns a newly created motion as @motion" do
        post :create, {:motion => valid_attributes}, valid_session
        assigns(:motion).should be_a(Motion)
        assigns(:motion).should be_persisted
      end

      it "redirects to the created motion" do
        post :create, {:motion => valid_attributes}, valid_session
        response.should redirect_to(Motion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved motion as @motion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Motion.any_instance.stub(:save).and_return(false)
        post :create, {:motion => { "organization" => "invalid value" }}, valid_session
        assigns(:motion).should be_a_new(Motion)
      end

      # it "re-renders the 'new' template" do
      #   # Trigger the behavior that occurs when invalid params are submitted
      #   Motion.any_instance.stub(:save).and_return(false)
      #   post :create, {:motion => { "organization" => "invalid value" }}, valid_session
      #   response.should render_template("new")
      # end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested motion" do
        motion = Motion.create! valid_attributes
        # Assuming there are no other motions in the database, this
        # specifies that the Motion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Motion.any_instance.should_receive(:update_attributes).with({ "organization" => "MyString" })
        put :update, {:id => motion.to_param, :motion => { "organization" => "MyString" }}, valid_session
      end

      it "assigns the requested motion as @motion" do
        motion = Motion.create! valid_attributes
        put :update, {:id => motion.to_param, :motion => valid_attributes}, valid_session
        assigns(:motion).should eq(motion)
      end

      it "redirects to the motion" do
        motion = Motion.create! valid_attributes
        put :update, {:id => motion.to_param, :motion => valid_attributes}, valid_session
        response.should redirect_to(motion)
      end
    end

    describe "with invalid params" do
      it "assigns the motion as @motion" do
        motion = Motion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Motion.any_instance.stub(:save).and_return(false)
        put :update, {:id => motion.to_param, :motion => { "organization" => "invalid value" }}, valid_session
        assigns(:motion).should eq(motion)
      end

      # it "re-renders the 'edit' template" do
      #   motion = Motion.create! valid_attributes
      #   # Trigger the behavior that occurs when invalid params are submitted
      #   Motion.any_instance.stub(:save).and_return(false)
      #   put :update, {:id => motion.to_param, :motion => { "organization" => "invalid value" }}, valid_session
      #   response.should render_template("edit")
      # end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested motion" do
      motion = Motion.create! valid_attributes
      expect {
        delete :destroy, {:id => motion.to_param}, valid_session
      }.to change(Motion, :count).by(-1)
    end

    it "redirects to the motions list" do
      motion = Motion.create! valid_attributes
      delete :destroy, {:id => motion.to_param}, valid_session
      response.should redirect_to(motions_url)
    end
  end

end
